[package]
name = "eliptic_curve_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

elliptic-curve = "0.13.8"
num-bigint = "0.4.4"
num-traits = "0.2.17"